repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(js/dist/|pkg-py/src/shinyjson/www/|pkg-r/inst/lib/shiny/)
      - id: end-of-file-fixer
        exclude: ^(js/dist/|pkg-py/src/shinyjson/www/|pkg-r/inst/lib/shiny/)
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
        args: [--config, pyproject.toml]
      - id: ruff-format
        args: [--config, pyproject.toml]
