# The Agent Skills that ship inside the installed package, at
# system.file("skills", package = "shinyreact") -- the path btw looks in, so it
# is a contract with the installer rather than an internal detail. The copies
# are generated by `make update-skills`; these tests are the drift guard.
#
# Mirrors pkg-py/tests/test_skills.py.

shipped_skills <- c("shinyreact-build-app", "shinyreact-convert-app")

test_that("skills are installed where btw looks", {
  for (name in shipped_skills) {
    expect_true(
      file.exists(system.file(
        "skills",
        name,
        "SKILL.md",
        package = "shinyreact"
      ))
    )
  }
})

test_that("skill frontmatter is a two-key YAML block", {
  for (name in shipped_skills) {
    lines <- readLines(
      system.file("skills", name, "SKILL.md", package = "shinyreact")
    )
    expect_equal(lines[[1]], "---")
    end <- which(lines == "---")[[2]]
    front <- lines[2:(end - 1)]

    # A description spilling onto a second line is invalid for the strict YAML
    # parsers installers use, and the failure is silent (the skill is skipped).
    expect_equal(front[[1]], paste0("name: ", name))
    expect_length(front, 2)
    expect_match(front[[2]], "^description: ")
    expect_false(grepl(
      ": ",
      sub("^description: ", "", front[[2]]),
      fixed = TRUE
    ))
  }
})

# The whole directory, not just SKILL.md -- a skill may carry references/, and
# a reference file that shipped stale would be invisible otherwise.
test_that("shipped copies match the repo's .claude/skills", {
  repo_skills <- testthat::test_path("..", "..", "..", ".claude", "skills")
  skip_if_not(dir.exists(repo_skills), "not running from the repo")

  tree <- function(root) {
    files <- sort(list.files(root, recursive = TRUE))
    stats::setNames(
      lapply(files, function(f) readLines(file.path(root, f))),
      files
    )
  }

  for (name in shipped_skills) {
    expect_equal(
      tree(system.file("skills", name, package = "shinyreact")),
      tree(file.path(repo_skills, name)),
      info = "run `make update-skills`"
    )
  }
})
