import * as ReactDOM from "react-dom/client";

import App from "./App";

// Mount only. Component definitions live in App.tsx so the refresh boundary is
// clean. Editing THIS file triggers a full reload (rare); editing App.tsx does
// not. Calling createRoot in a file that also defines components would defeat
// Fast Refresh.
// No index.html in this example -- the server page is generated by
// set_react_page() discovery, so the app appends its own mount container.
ReactDOM.createRoot(
  document.body.appendChild(document.createElement("div")),
).render(<App />);
