import "@/index.css";

import App from "@/App";

const { React, ReactDOM } = window.shinyreact;

// No index.html in this example -- the server page is generated by
// set_react_page() discovery, so the app appends its own mount container.
const root = ReactDOM.createRoot(
  document.body.appendChild(document.createElement("div")),
);
root.render(React.createElement(App));
