"""The Agent Skills that ship inside the installed package.

`library-skills` scans site-packages for `<package>/.agents/skills/*/SKILL.md`,
so the path is a contract with the installer, not an internal detail. The
copies are generated by `make update-skills`; these tests are the drift guard.

Mirrored by pkg-r/tests/testthat/test-skills.R.
"""

from pathlib import Path

import pytest
import shinyreact

SKILLS_DIR = Path(shinyreact.__file__).parent / ".agents" / "skills"
SHIPPED = ["shinyreact-build-app", "shinyreact-convert-app"]
REPO_SKILLS = Path(__file__).parents[2] / ".claude" / "skills"


@pytest.mark.parametrize("name", SHIPPED)
def test_skill_is_installed_where_library_skills_looks(name: str):
    assert (SKILLS_DIR / name / "SKILL.md").is_file()


@pytest.mark.parametrize("name", SHIPPED)
def test_skill_frontmatter(name: str):
    lines = (SKILLS_DIR / name / "SKILL.md").read_text().splitlines()
    assert lines[0] == "---"
    end = lines.index("---", 1)
    front = lines[1:end]

    # A description spilling onto a second line is invalid for the strict YAML
    # parsers installers use, and the failure is silent (the skill is skipped).
    assert front[0] == f"name: {name}"
    assert front[1].startswith("description: ")
    assert len(front) == 2
    assert ": " not in front[1][len("description: ") :], "quote the description"


@pytest.mark.parametrize("name", SHIPPED)
def test_shipped_copy_matches_repo(name: str):
    if not REPO_SKILLS.is_dir():
        pytest.skip("running against an installed package, not the repo")
    expected = (REPO_SKILLS / name / "SKILL.md").read_text()
    assert (SKILLS_DIR / name / "SKILL.md").read_text() == expected, (
        "run `make update-skills`"
    )
