"""The Agent Skills that ship inside the installed package.

`library-skills` scans site-packages for `<package>/.agents/skills/*/SKILL.md`,
so the path is a contract with the installer, not an internal detail. The
copies are generated by `make update-skills`; these tests are the drift guard.

Mirrored by pkg-r/tests/testthat/test-skills.R.
"""

import re
from pathlib import Path

import pytest
import shinyreact

SKILLS_DIR = Path(shinyreact.__file__).parent / ".agents" / "skills"
SHIPPED = ["shinyreact-build-app", "shinyreact-convert-app"]
REPO_SKILLS = Path(__file__).parents[2] / ".claude" / "skills"


@pytest.mark.parametrize("name", SHIPPED)
def test_skill_is_installed_where_library_skills_looks(name: str):
    assert (SKILLS_DIR / name / "SKILL.md").is_file()


@pytest.mark.parametrize("name", SHIPPED)
def test_skill_frontmatter(name: str):
    lines = (SKILLS_DIR / name / "SKILL.md").read_text().splitlines()
    assert lines[0] == "---"
    end = lines.index("---", 1)
    front = lines[1:end]

    # A description spilling onto a second line is invalid for the strict YAML
    # parsers installers use, and the failure is silent (the skill is skipped).
    assert front[0] == f"name: {name}"
    assert front[1].startswith("description: ")
    assert len(front) == 2
    # An unquoted `: ` turns the scalar into a mapping and breaks the parse;
    # a quoted value is fine, so only check the unquoted case.
    value = front[1][len("description: ") :]
    if not (value.startswith('"') and value.endswith('"')):
        assert ": " not in value, "quote the description"


@pytest.mark.parametrize("name", SHIPPED)
def test_skill_links_are_reachable_by_a_user(name: str):
    """A shipped skill is read from site-packages by someone with no checkout.

    So it may not point at a repo path (which resolves to nothing there), and it
    may not point at a contributor-only document even by URL -- that material
    gets inlined instead. Public `examples/` links are fine.

    Not mirrored in R: this is a property of the shared source file, not of
    either package, so asserting it once is enough.
    """
    text = (SKILLS_DIR / name / "SKILL.md").read_text()

    for path in (".claude/", "examples/", "pkg-py/", "pkg-r/", "pkg-js/"):
        assert f"]({path}" not in text, f"relative Markdown link to {path}"

    # Contributor-only trees. A GitHub URL into one still sends a user somewhere
    # that assumes the repo, so inline what matters rather than linking it.
    for internal in (".claude/", "decisions/", "DESIGN.md", "CLAUDE.md", "FEATURES.md"):
        assert internal not in text, f"{internal} is contributor-only -- inline it"

    # Bare repo paths in prose are the same problem without the link syntax.
    # Drop resolved links first, or `[`examples/`](https://…)` reads as bare.
    prose = re.sub(r"\[[^\]]*\]\([^)]*\)", "", text)
    assert "`examples/" not in prose, "bare `examples/...` path -- link it"


@pytest.mark.parametrize("name", SHIPPED)
def test_shipped_copy_matches_repo(name: str):
    """The whole directory, not just SKILL.md -- a skill may carry references/,
    and a reference file that shipped stale would be invisible otherwise."""
    if not REPO_SKILLS.is_dir():
        pytest.skip("running against an installed package, not the repo")

    def tree(root: Path) -> dict[str, str]:
        return {
            str(p.relative_to(root)): p.read_text()
            for p in sorted(root.rglob("*"))
            if p.is_file()
        }

    assert tree(SKILLS_DIR / name) == tree(REPO_SKILLS / name), (
        "run `make update-skills`"
    )
